Repository GeminiDRSoftware/astrodata, pull requests merged in 2024-07, with the labels that each got.

#21 Remove argument for poetry install in quickstart
  docs/quickstart.rst
Labels: documentation

#20 Fix typos in documentation
  docs/quickstart.rst
Labels: documentation

#24 Update README.md poetry description.
  README.md
Labels: documentation

#32 [DOC] Update README.md with citation information
  README.md
Labels: documentation, maintenance

#34 Actions runner ip logging
  .github/workflows/testing.yml
Labels: enhancement, CI/CD
